server:
  port: 8099

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8889
  cloud:
    gateway:
      routes:
        - id: LOGIN
          uri: lb://LOGIN
          predicates:
            - Path=/login/**